POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "SupportingForU",
  "password": "a123"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name": "Patricio",
  "lastname": "Fernandez Ionadi",
  "birth": "8/9/92",
  "email": "poker@mail.com",
  "password": "a123",
  "username": "SupportingForU"
}
